// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1B_mHuXW0ghIDlGPgZOLpluyjB8M7Gc',
    appId: '1:234523168738:android:eb04097bdfac4b514ff3bb',
    messagingSenderId: '234523168738',
    projectId: 'super-swipe-erin-2025',
    storageBucket: 'super-swipe-erin-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBi8W_OoKaiDANFHpkhaM79hyD_XxPpB0',
    appId: '1:234523168738:ios:214ed6bcd49ff8174ff3bb',
    messagingSenderId: '234523168738',
    projectId: 'super-swipe-erin-2025',
    storageBucket: 'super-swipe-erin-2025.firebasestorage.app',
    iosBundleId: 'com.superswipe.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMgMI9hfQyhpOngDOP-Wi44YaN2QXJecI',
    appId: '1:234523168738:web:ca977802e42fcaf04ff3bb',
    messagingSenderId: '234523168738',
    projectId: 'super-swipe-erin-2025',
    authDomain: 'super-swipe-erin-2025.firebaseapp.com',
    storageBucket: 'super-swipe-erin-2025.firebasestorage.app',
  );

}